---
- name: ensure nova database user is present
  mysql_user: >
      name=nova
      host=$item
      password=$nova_db_password
      priv=nova.*:ALL
  delegate_to: ${first_host.controller}
  with_items:
    - $my_int_ip

- name: ensure nova-compute package is installed
  apt: pkg=$item
  with_items:
    - nova-compute-qemu
    - python-mysqldb

- name: ensure nova.conf file is configured
  template: >
        src=nova.conf
        dest=/etc/nova/nova.conf
        owner=nova group=nova mode=0660
        backup=yes

- name: ensure nova.conf file is configured (update check)
  template: >
        src=nova.conf
        dest=/etc/nova/.nova.conf.backend
        owner=nova group=nova mode=0660
        backup=yes
  notify:
    - restart nova-compute
    
- name: ensure nova-compute.conf file is configured
  copy: >
        src=nova-compute.conf
        dest=/etc/nova/nova-compute.conf
        owner=nova group=nova mode=0660
        backup=yes
  notify:
    - restart nova-compute

- name: ensure /etc/libvirt/qemu.conf file is configured
  copy: >
        src=qemu.conf
        dest=/etc/libvirt/qemu.conf
        owner=root group=root mode=0660
        backup=yes
  notify:
    - restart libvirt

- name: ensure virbr0 is absent
  shell: virsh net-destroy default && virsh net-undefine default
  when: "'virbr0' in ansible_interfaces"
  ignore_errors: True
  notify: restart libvirt

- meta: flush_handlers
