---
- name: Checking Variables
  hosts: all[:1]
  gather_facts: yes

  tasks:
    - action: setup

    - name: Check controller_ip is set
      fail: msg="controller_ip is automatically configured. Run the playbook again."
      when: "controller_ip is not defined or not controller_ip"

    - name: Check frontend_int_ip is set
      fail: msg="frontend_int_ip is automatically configured. Run the playbook again."
      when: "frontend_int_ip is not defined or not frontend_int_ip"

    - name: Check frontend_ext_ip is set
      fail: msg="frontend_ext_ip is automatically configured. Run the playbook again."
      when: "frontend_ext_ip is not defined or not frontend_ext_ip"
