---
- name: controller_ip
  hosts: all[:1]
  sudo: yes

  tasks:
    - name: Check controller_ip is set
      command: /bin/true
      when: "controller_ip is not defined or not controller_ip"
      notify:
        - Ensure controller_ip is set in group_var_all file

  handlers:
    - name: Ensure controller_ip is set in group_var_all file
      local_action: >
          lineinfile
          dest=../../group_vars/all
          regexp="^controller_ip:"
          line="controller_ip: {{ hostvars[primary_controller_host]['my_int_ip'] }}"
