---
- name: Host Variables
  hosts: all
  gather_facts: yes
  sudo: yes

  tasks:
    - name: ensure my_int_ip is a fact variable
      action: set_fact
      args:
        my_int_ip: "{{ my_int_ip }}"
  
    - name: ensure my_ext_ip is a fact variable
      action: set_fact
      args:
        my_ext_ip: "{{ my_ext_ip }}"
  
    - name: ensure my_ext_ip is a fact variable (br-ex)
      action: set_fact
      args:
        my_ext_ip: "{{ ansible_br_ex['ipv4']['address'] }}"
      when: "ansible_br_ex is defined"
