---
- name: Host Variables
  hosts: all
  gather_facts: yes
  sudo: yes

  tasks:
    - name: ensure my_int_ip is a fact variable
      action: set_fact
      args:
        my_int_ip: "{{ my_int_ip }}"
  
    - name: ensure my_ext_ip is a fact variable
      action: set_fact
      args:
        my_ext_ip: "{{ my_ext_ip }}"
  
    - name: ensure my_ext_ip is a fact variable (br-ex)
      action: set_fact
      args:
        my_ext_ip: "{{ ansible_br_ex['ipv4']['address'] }}"
      when: "ansible_br_ex is defined"
  
    - name: Ensure controller_ip is set.
      local_action: >
          lineinfile
          dest=../../group_vars/all
          regexp="^controller_ip:"
          line="controller_ip: {{ hostvars[primary_controller_host]['my_int_ip'] }}"
      when: "controller_ip is not defined"

    - name: Ensure frontend_int_ip is set.
      local_action: >
          lineinfile
          dest=../../group_vars/all
          regexp="^frontend_int_ip:"
          line="frontend_int_ip: {{ hostvars[primary_frontend_host]['my_int_ip'] }}"
      when: "frontend_int_ip is not defined"

    - name: Ensure frontend_ext_ip is set.
      local_action: >
          lineinfile
          dest=../../group_vars/all
          regexp="^frontend_ext_ip:"
          line="frontend_ext_ip: {{ hostvars[primary_frontend_host]['my_ext_ip'] }}"
      when: "frontend_ext_ip is not defined"

    - name: gather the last facts
      action: setup
