---
- name: ensure nova database is present
  mysql_db: name=nova
  delegate_to: ${first_host.controller}
  
- name: ensure nova database user is present
  mysql_user: >
        name=nova
        host=$item
        password=$nova_db_password
        priv=nova.*:ALL
  with_items:
    - $my_int_ip
  delegate_to: ${first_host.controller}
  notify:
    - ensure services are restarted
 
- name: ensure nova packages are installed
  apt: pkg=$item
  with_items:
    - nova-cert
    - nova-conductor
    - nova-consoleauth
    - nova-scheduler
    - python-novaclient
    - python-mysqldb
  notify:
    - ensure services are restarted

- name: ensure nova.conf file is configured
  template: >
        src=nova.conf
        dest=/etc/nova/nova.conf
        owner=nova
        group=nova
        mode=0660
        backup=yes

- name: ensure nova.conf file is configured (update check)
  template: >
        src=nova.conf
        dest=/etc/nova/.nova.conf.controller
        owner=nova
        group=nova
        mode=0660
        backup=yes
  notify:
    - ensure services are restarted

- name: ensure database is synced
  command: /usr/bin/nova-manage db sync

- meta: flush_handlers
