---
- name: OpenStack Block Storage (Controller)
  hosts: controller
  sudo: yes

  tasks:
    - name: ensure cinder database is present
      mysql_db: name=cinder
      when: "ansible_hostname == first_host['controller']"
      notify:
        - restart cinder services
      
    - name: ensure cinder database user is present
      mysql_user: >
          name=cinder
          host=$item
          password=$cinder_db_password
          priv=cinder.*:ALL
      with_items:
        - $my_int_ip
      delegate_to: ${first_host.controller}
    
    - name: ensure cinder-related packages are installed
      apt: pkg=$item
      with_items:
        - cinder-common
        - cinder-scheduler
        - python-cinderclient
        - python-mysqldb
    
    - name: ensure cinder.conf file is configured
      template: >
          src=files/cinder.conf
          dest=/etc/cinder/cinder.conf
          owner=cinder group=cinder mode=0644 backup=yes
    
    - name: ensure cinder.conf file is configured (update check)
      template: >
          src=files/cinder.conf
          dest=/etc/cinder/.cinder.conf.controller
          owner=cinder group=cinder mode=0644 backup=yes
      notify:
        - restart cinder services
    
    - name: sync cinder db
      command: cinder-manage db sync
      when: "ansible_hostname == first_host['controller']"
    
  handlers:
    - name: restart cinder services
      service: name=cinder-scheduler state=restarted
