---
- name: OpenStack Compute (Controller)
  hosts: controller
  sudo: yes

  tasks:
    - name: ensure nova database is present
      mysql_db: name=nova
      when: "ansible_hostname == primary_controller_host"
    
    - name: ensure nova database user is present
      mysql_user: >
            name=nova
            host=$item
            password=$nova_db_password
            priv=nova.*:ALL
      with_items:
        - $my_int_ip
      delegate_to: ${primary_controller_host}
      notify:
        - ensure services are restarted
   
    - name: ensure nova packages are installed
      apt: pkg=$item
      with_items:
        - nova-cert
        - nova-conductor
        - nova-consoleauth
        - nova-scheduler
        - python-novaclient
        - python-mysqldb
        - python-memcache
      notify:
        - ensure services are restarted
  
    - name: ensure nova.conf file is configured
      template: >
            src=files/nova.conf
            dest=/etc/nova/nova.conf
            owner=nova
            group=nova
            mode=0660
            backup=yes
  
    - name: ensure nova.conf file is configured (update check)
      template: >
            src=files/nova.conf
            dest=/etc/nova/.nova.conf.controller
            owner=nova
            group=nova
            mode=0660
            backup=yes
      notify:
        - ensure services are restarted
    
    - name: ensure database is synced
      command: /usr/bin/nova-manage db sync
      when: "ansible_hostname == primary_controller_host"
    
  handlers:
    - name: ensure services are restarted
      service: name=$item state=restarted
      with_items:
        - nova-cert
        - nova-consoleauth
        - nova-conductor
        - nova-scheduler
