---
- name: admin_password
  hosts: all[:1]
  sudo: yes

  tasks:
    - name: Generate a password string for admin_password
      local_action: >
          shell pwgen -c -n 16 1
      register: password
      when: "admin_password is not defined or not admin_password"
      notify:
        - Ensure admin_password is in group_var_all file

  handlers:
    - name: Ensure admin_password is in group_var_all file
      local_action: >
          lineinfile
          dest=../../group_vars/all
          regexp="^admin_password:"
          line="admin_password: ${password.stdout_lines}"
