---
- name: admin_token
  hosts: all[:1]
  sudo: yes

  tasks:
    - name: Generate a password string for admin_token
      local_action: >
          shell pwgen -c -n 16 1
      register: password
      when: "admin_token is not defined or not admin_token"
      notify:
        - Ensure admin_token is set in group_var_all file
        - Ensure admin_token is a fact variable

  handlers:
    - name: Ensure admin_token is set in group_var_all file
      local_action: >
          lineinfile
          dest=../../group_vars/all
          regexp="^admin_token:"
          line="admin_token: ${password.stdout_lines}"

    - name: Ensure admin_token is a fact variable
      set_fact: admin_token=${password.stdout_lines}
