---
- name: cinder_db_password
  hosts: all[:1]
  sudo: yes

  tasks:
    - name: Generate a password string for cinder_db_password
      local_action: >
          shell pwgen -c -n 16 1
      register: password
      when: "cinder_db_password is not defined or not cinder_db_password"
      notify:
        - Ensure cinder_db_password is set in group_var_all file
        - Ensure cinder_db_password is a fact variable

  handlers:
    - name: Ensure cinder_db_password is set in group_var_all file
      local_action: >
          lineinfile
          dest=../../group_vars/all
          regexp="^cinder_db_password:"
          line="cinder_db_password: ${password.stdout_lines}"

    - name: Ensure cinder_db_password is a fact variable
      set_fact: cinder_db_password=${password.stdout_lines}
