---
- name: cinder_identity_password
  hosts: all[:1]
  sudo: yes

  tasks:
    - name: Generate a password string for cinder_identity_password
      local_action: >
          shell pwgen -c -n 16 1
      register: password
      when: "cinder_identity_password is not defined or not cinder_identity_password"
      notify:
        - Ensure cinder_identity_password is set in group_var_all file

  handlers:
    - name: Ensure cinder_identity_password is set in group_var_all file
      local_action: >
          lineinfile
          dest=../../group_vars/all
          regexp="^cinder_identity_password:"
          line="cinder_identity_password: ${password.stdout_lines}"
