---
- name: glance_identity_password
  hosts: all[:1]
  sudo: yes

  tasks:
    - name: Generate a password string for glance_identity_password
      local_action: >
          shell pwgen -c -n 16 1
      register: password
      when: "glance_identity_password is not defined or not glance_identity_password"
      notify:
        - Ensure glance_identity_password is set in group_var_all file
        - Ensure glance_identity_password is a fact variable

  handlers:
    - name: Ensure glance_identity_password is set in group_var_all file
      local_action: >
          lineinfile
          dest=../../group_vars/all
          regexp="^glance_identity_password:"
          line="glance_identity_password: ${password.stdout_lines}"

    - name: Ensure glance_identity_password is a fact variable
      set_fact: glance_identity_password=${password.stdout_lines}
