---
- name: heartbeat_secret_key
  hosts: all[:1]
  sudo: yes

  tasks:
    - name: Generate a password string for heartbeat_secret_key
      local_action: >
          shell pwgen -c -n 16 1
      register: password
      when: "heartbeat_secret_key is not defined or not heartbeat_secret_key"
      notify:
        - Ensure heartbeat_secret_key is set in group_var_all file

  handlers:
    - name: Ensure heartbeat_secret_key is set in group_var_all file
      local_action: >
          lineinfile
          dest=../../group_vars/all
          regexp="^heartbeat_secret_key:"
          line="heartbeat_secret_key: ${password.stdout_lines}"
