---
- name: Host Variables
  hosts: all[:1]
  gather_facts: yes
  sudo: yes

  tasks:
    - name: Ensure primary_controller_host is set.
      local_action: >
          lineinfile
          dest=../../group_vars/all
          regexp="^primary_controller_host:"
          line="primary_controller_host: {{ groups['controller'][0] }}"
      when: "primary_controller_host is not defined"

    - name: Ensure primary_frontend_host is set.
      local_action: >
          lineinfile
          dest=../../group_vars/all
          regexp="^primary_frontend_host:"
          line="primary_frontend_host: {{ groups['frontend'][0] }}"
      when: "primary_frontend_host is not defined"

    - name: Ensure pwgen is present.
      local_action: >
          apt package=pwgen

    - name: Ensure root_db_password is set.
      local_action: >
          lineinfile
          dest=../../group_vars/all
          regexp="^root_db_password:"
          line="root_db_password: {{ lookup('pipe', 'pwgen -c -n 16') }}"
      when: "root_db_password is not defined"

    - name: Ensure keystone_db_password is set.
      local_action: >
          lineinfile
          dest=../../group_vars/all
          regexp="^keystone_db_password:"
          line="keystone_db_password: {{ lookup('pipe', 'pwgen -c -n 16') }}"
      when: "keystone_db_password is not defined"

    - name: Ensure glance_db_password is set.
      local_action: >
          lineinfile
          dest=../../group_vars/all
          regexp="^glance_db_password:"
          line="glance_db_password: {{ lookup('pipe', 'pwgen -c -n 16') }}"
      when: "glance_db_password is not defined"

    - name: Ensure nova_db_password is set.
      local_action: >
          lineinfile
          dest=../../group_vars/all
          regexp="^nova_db_password:"
          line="nova_db_password: {{ lookup('pipe', 'pwgen -c -n 16') }}"
      when: "nova_db_password is not defined"

    - name: Ensure quantum_db_password is set.
      local_action: >
          lineinfile
          dest=../../group_vars/all
          regexp="^quantum_db_password:"
          line="quantum_db_password: {{ lookup('pipe', 'pwgen -c -n 16') }}"
      when: "quantum_db_password is not defined"

    - name: Ensure cinder_db_password is set.
      local_action: >
          lineinfile
          dest=../../group_vars/all
          regexp="^cinder_db_password:"
          line="cinder_db_password: {{ lookup('pipe', 'pwgen -c -n 16') }}"
      when: "cinder_db_password is not defined"

    - name: Ensure glance_identity_password is set.
      local_action: >
          lineinfile
          dest=../../group_vars/all
          regexp="^glance_identity_password:"
          line="glance_identity_password: {{ lookup('pipe', 'pwgen -c -n 16') }}"
      when: "glance_identity_password is not defined"

    - name: Ensure nova_identity_password is set.
      local_action: >
          lineinfile
          dest=../../group_vars/all
          regexp="^nova_identity_password:"
          line="nova_identity_password: {{ lookup('pipe', 'pwgen -c -n 16') }}"
      when: "nova_identity_password is not defined"

    - name: Ensure ec2_identity_password is set.
      local_action: >
          lineinfile
          dest=../../group_vars/all
          regexp="^ec2_identity_password:"
          line="ec2_identity_password: {{ lookup('pipe', 'pwgen -c -n 16') }}"
      when: "ec2_identity_password is not defined"

    - name: Ensure swift_identity_password is set.
      local_action: >
          lineinfile
          dest=../../group_vars/all
          regexp="^swift_identity_password:"
          line="swift_identity_password: {{ lookup('pipe', 'pwgen -c -n 16') }}"
      when: "swift_identity_password is not defined"

    - name: Ensure quantum_identity_password is set.
      local_action: >
          lineinfile
          dest=../../group_vars/all
          regexp="^quantum_identity_password:"
          line="quantum_identity_password: {{ lookup('pipe', 'pwgen -c -n 16') }}"
      when: "quantum_identity_password is not defined"

    - name: Ensure cinder_identity_password is set.
      local_action: >
          lineinfile
          dest=../../group_vars/all
          regexp="^cinder_identity_password:"
          line="cinder_identity_password: {{ lookup('pipe', 'pwgen -c -n 16') }}"
      when: "cinder_identity_password is not defined"

    - name: Ensure admin_token is set.
      local_action: >
          lineinfile
          dest=../../group_vars/all
          regexp="^admin_token:"
          line="admin_token: {{ lookup('pipe', 'pwgen -c -n 16') }}"
      when: "admin_token is not defined"

    - name: Ensure admin_password is set.
      local_action: >
          lineinfile
          dest=../../group_vars/all
          regexp="^admin_password:"
          line="admin_password: {{ lookup('pipe', 'pwgen -c -n 16') }}"
      when: "admin_password is not defined"
