---
- name: Host Variables
  hosts: all
  gather_facts: yes
  sudo: yes

  tasks:
    - name: gather the last facts
      action: setup
  
    - name: ensure my_int_ip is a fact variable
      action: set_fact
      args:
        my_int_ip: "{{ my_int_ip }}"
  
    - name: ensure my_ext_ip is a fact variable
      action: set_fact
      args:
        my_ext_ip: "{{ my_ext_ip }}"
  
    - name: ensure my_ext_ip is a fact variable (br-ex)
      action: set_fact
      args:
        my_ext_ip: "{{ ansible_br_ex['ipv4']['address'] }}"
      when: "ansible_br_ex is defined"
  
    - name: ensure frontend_ext_ip is set
      action: set_fact
      args:
        frontend_ext_ip: "{{ hostvars[first_host['frontend']]['my_ext_ip'] }}"
      when: "frontend_ext_ip is not defined"
  
    - name: ensure frontend_int_ip is set
      action: set_fact
      args:
        frontend_int_ip: "{{ hostvars[first_host['frontend']]['my_int_ip'] }}"
      when: "frontend_int_ip is not defined"
  
    - name: ensure controller_ip is set
      action: set_fact
      args:
        controller_ip: "{{ hostvars[first_host['controller']]['my_int_ip'] }}"
      when: "controller_ip is not defined"
