---
- name: nova_identity_password
  hosts: all[:1]
  sudo: yes

  tasks:
    - name: Generate a password string for nova_identity_password
      local_action: >
          shell pwgen -c -n 16 1
      register: password
      when: "nova_identity_password is not defined or not nova_identity_password"
      notify:
        - Ensure nova_identity_password is set in group_var_all file
        - Ensure nova_identity_password is a fact variable

  handlers:
    - name: Ensure nova_identity_password is set in group_var_all file
      local_action: >
          lineinfile
          dest=../../group_vars/all
          regexp="^nova_identity_password:"
          line="nova_identity_password: ${password.stdout_lines}"

    - name: Ensure nova_identity_password is a fact variable
      set_fact: nova_identity_password=${password.stdout_lines}
