---
- name: nova_db_password
  hosts: all[:1]
  sudo: yes

  tasks:
    - name: Generate a password string for nova_db_password
      local_action: >
          shell pwgen -c -n 16 1
      register: password
      when: "nova_db_password is not defined or not nova_db_password"
      notify:
        - Ensure nova_db_password is set in group_var_all file
        - Ensure nova_db_password is a fact variable

  handlers:
    - name: Ensure nova_db_password is set in group_var_all file
      local_action: >
          lineinfile
          dest=../../group_vars/all
          regexp="^nova_db_password:"
          line="nova_db_password: ${password.stdout_lines}"

    - name: Ensure nova_db_password is a fact variable
      set_fact: nova_db_password=${password.stdout_lines}
