---
- name: root_db_password
  hosts: all[:1]
  sudo: yes

  tasks:
    - name: Generate a password string for root_db_password
      local_action: >
          shell pwgen -c -n 16 1
      register: password
      when: "root_db_password is not defined or not root_db_password"
      notify:
        - Ensure root_db_password is set in group_var_all file
        - Ensure root_db_password is a fact variable

  handlers:
    - name: Ensure root_db_password is set in group_var_all file
      local_action: >
          lineinfile
          dest=../../group_vars/all
          regexp="^root_db_password:"
          line="root_db_password: ${password.stdout_lines}"

    - name: Ensure root_db_password is a fact variable
      set_fact: root_db_password=${password.stdout_lines}
