---
- name: swift_identity_password
  hosts: all[:1]
  sudo: yes

  tasks:
    - name: Generate a password string for swift_identity_password
      local_action: >
          shell pwgen -c -n 16 1
      register: password
      when: "swift_identity_password is not defined or not swift_identity_password"
      notify:
        - Ensure swift_identity_password is set in group_var_all file

  handlers:
    - name: Ensure swift_identity_password is set in group_var_all file
      local_action: >
          lineinfile
          dest=../../group_vars/all
          regexp="^swift_identity_password:"
          line="swift_identity_password: ${password.stdout_lines}"
