---
- name: OpenStack Identity
  hosts: frontend
  gather_facts: yes
  sudo: yes

  tasks:
    - name: ensure keystone database is present
      mysql_db: name=keystone
      delegate_to: ${primary_controller_host}
      when: "ansible_hostname == primary_frontend_host"
    
    - name: ensure keystone database user is present
      mysql_user: >
          name=keystone
          host=$item
          password=${keystone_db_password}
          priv=keystone.*:ALL
      with_items:
        - $my_int_ip
      delegate_to: ${primary_controller_host}
    
    - name: ensure keystone package is installed
      apt: pkg=$item
      with_items:
        - keystone
        - python-mysqldb
    
    - name: ensure keystone service running
      service: name=keystone state=started
    
    - name: ensure sqlite keystone database is deleted
      file: >
          dest=/var/lib/keystone/keystone.db
          state=absent
    
    - name: ensure keystone.conf file is configured
      template: >
          src=files/keystone.conf
          dest=/etc/keystone/keystone.conf
          owner=keystone
          group=keystone
          mode=0600
      notify: restart keystone
    
    - name: ensure keystone database is initialized
      keystone_manage: action=db_sync
      when: "ansible_hostname == primary_frontend_host"
      notify: restart keystone
    
  handlers:
    - name: restart keystone
      service: name=keystone state=restarted
