---
- name: OpenStack Networking (Frontend)
  hosts: frontend
  sudo: yes

  tasks:
    - name: ensure quantum database is present
      mysql_db: name=quantum
      delegate_to: ${primary_controller_host}
      when: "ansible_hostname == primary_frontend_host"
    
    - name: ensure quantum database user is present
      mysql_user: >
            name=quantum
            host=$item
            password=$quantum_db_password
            priv=quantum.*:ALL
      with_items:
        - $my_int_ip
      delegate_to: ${primary_controller_host}
    
    - name: ensure quantum-server and CLI packages are installed
      apt: pkg=$item force=yes
      with_items:
        - quantum-server
        - python-cliff
        - python-pyparsing
        - python-mysqldb
        - python-sqlalchemy
        - quantum-plugin-openvswitch
        - python-quantumclient
    
    - name: ensure ovs_quantum_plugin.ini file is configured
      template: >
            src=files/ovs_quantum_plugin.ini
            dest=/etc/quantum/plugins/openvswitch/ovs_quantum_plugin.ini
            owner=quantum group=quantum mode=0660 backup=yes
    
    - name: ensure ovs_quantum_plugin.ini file is configured (update check)
      template: >
            src=files/ovs_quantum_plugin.ini
            dest=/etc/quantum/plugins/openvswitch/.ovs_quantum_plugin.ini.controller
            owner=quantum group=quantum mode=0660 backup=yes
      notify:
        - restart quantum-server
    
    - name: ensure quantum.conf file is configured
      template: >
            src=files/quantum.conf
            dest=/etc/quantum/quantum.conf
            owner=quantum group=quantum mode=0660 backup=yes
    
    - name: ensure quantum.conf file is configured (update check)
      template: >
            src=files/quantum.conf
            dest=/etc/quantum/.quantum.conf.contoller
            owner=quantum group=quantum mode=0660 backup=yes
      notify:
        - restart quantum-server
    
  handlers:
    - name: restart quantum-server
      service: name=quantum-server state=restarted
