---
- name: ensure quantum database is present
  mysql_db: name=quantum
  delegate_to: ${first_host.controller}

- name: ensure quantum database user is present
  mysql_user: >
        name=quantum
        host=$item
        password=$quantum_db_password
        priv=quantum.*:ALL
  with_items:
    - $my_int_ip
  delegate_to: ${first_host.controller}

- name: ensure quantum-server and CLI packages are installed
  apt: pkg=$item
  with_items:
    - quantum-server
    - python-cliff
    - python-pyparsing
    - python-mysqldb
    - python-sqlalchemy
    - quantum-plugin-openvswitch
    - python-quantumclient

- name: ensure ovs_quantum_plugin.ini file is configured
  template: >
        src=ovs_quantum_plugin.ini
        dest=/etc/quantum/plugins/openvswitch/ovs_quantum_plugin.ini
        owner=quantum group=quantum mode=0660 backup=yes

- name: ensure ovs_quantum_plugin.ini file is configured (update check)
  template: >
        src=ovs_quantum_plugin.ini
        dest=/etc/quantum/plugins/openvswitch/.ovs_quantum_plugin.ini.controller
        owner=quantum group=quantum mode=0660 backup=yes
  notify:
    - restart quantum-server

- name: ensure quantum.conf file is configured
  template: >
        src=quantum.conf
        dest=/etc/quantum/quantum.conf
        owner=quantum group=quantum mode=0660 backup=yes

- name: ensure quantum.conf file is configured (update check)
  template: >
        src=quantum.conf
        dest=/etc/quantum/.quantum.conf.contoller
        owner=quantum group=quantum mode=0660 backup=yes
  notify:
    - restart quantum-server

- meta: flush_handlers
