---
- name: NTP Client
  hosts: all
  sudo: yes

  tasks:
    - name: ensure ntp package is not installed
      apt: pkg=ntp state=absent
      when: "ntp_server not in ansible_all_ipv4_addresses"
  
    - name: ensure ntpdate package is installed
      apt: pkg=ntpdate force=yes
      when: "ntp_server not in ansible_all_ipv4_addresses"
  
    - name: ensure /etc/cron.daily/ntpdate file is configured
      template: >
            src=files/ntpdate 
            dest=/etc/cron.daily/ntpdate 
            owner=root group=root mode=0755
