---
- name: set up controller node(s)
  hosts: controller
  gather_facts: yes
  sudo: yes
  roles:
    - mysql
    - rabbitmq
    - memcached
    - image_controller
    - volume_controller
    - compute_controller
