---
- name: OpenStack Image Service (Controller)
  hosts: controller
  sudo: yes

  tasks:
    - name: ensure glance database is present
      mysql_db: name=glance
      when: "ansible_hostname == primary_controller_host"
      notify:
        - initialize the database
        - restart glance-registry
    
    - name: ensure glance database user is present
      mysql_user: >
          name=glance
          host=$item
          password=${glance_db_password}
          priv=glance.*:ALL
      with_items:
        - $my_int_ip
      delegate_to: ${primary_controller_host}
      notify:
        - initialize the database
        - restart glance-registry
    
    - name: ensure glance is installed
      apt: pkg=$item
      with_items:
        - glance
        - python-glanceclient
        - python-mysqldb
    
    - name: ensure glance sqlite is deleted
      file: >
          dest=/var/lib/glance/glance.sqlite
          state=absent
    
    - name: ensure glance-registry.conf file file is configured
      template: >
          src=files/glance-registry.conf
          dest=/etc/glance/glance-registry.conf
          owner=glance
          group=glance
          mode=0600
          backup=yes
      notify:
        - initialize the database
        - restart glance-registry
    
  handlers:
    - name: restart glance-registry
      service: name=glance-registry state=restarted
    
    - name: initialize the database
      glance_manage: action=dbsync
      when: "ansible_hostname == primary_controller_host"
    
