---
- name: OpenStack Image Service (Fixture(s))
  hosts: frontend
  sudo: yes
  vars_files:
    - vars/main.yml
  
  tasks:
    - name: ensure temporary image directory exists
      file: >
          dest=/tmp/images
          state=directory
      delegate_to: ${first_host.frontend}
    
    - name: ensure test image has been obtained
      get_url: >
          url=${item.url}
          dest=/tmp/images/${item.name}
      with_items: $glance_images
      environment: "{{ proxy_env }}"
      delegate_to: ${first_host.frontend}
    
    - name: ensure cirros image is registered
      glance: >
          name=${item.name}
          file=/tmp/images/${item.name}
          disk_format=${item.disk_format}
          is_public=true
          user=admin
          tenant=demo
          password=secrete
          region=RegionOne
          auth_url=http://${frontend_ext_ip}:5000/v2.0
      with_items: $glance_images
      delegate_to: ${first_host.frontend}
