---
- name: gather the latest facts (for br-ex)
  action: setup

- name: ensure the internal network interface is up.
  command: dhclient -1 {{ my_int_if }}
  when: "'ipv4' not in my_int_obj"

- name: ensure the external network interface is up.
  command: ifconfig {{ my_ext_if }} 0.0.0.0 up

- name: ensure br-ex is up.
  command: dhclient -1 br-ex
  when: "ansible_br_ex is defined and 'ipv4' not in ansible_br_ex"

- name: gather the latest facts
  action: setup

- name: ensure /etc/network/interfaces file is configured
  template: >
        src=interfaces
        dest=/etc/network/interfaces
        owner=root
        group=root
        mode=0644
  notify: 
    - restart network

- meta: flush_handlers
